# Utilise la dernière image officielle de Nginx comme base
FROM nginx:latest

# Copie notre fichier de configuration proxy personnalisé à l'emplacement par défaut de Nginx
COPY ./proxy.conf /etc/nginx/conf.d/default.conf
