server {
    # Le serveur proxy écoute sur le port standard HTTP (80)
    listen 80;

    # Règle par défaut : toutes les requêtes arrivant sur '/' sont redirigées vers le front-end
    location / {
        # 'front-end' correspond au nom du service défini dans docker-compose.yml
        proxy_pass http://front-end:9000;
    }

    # Règle spécifique : toutes les requêtes commençant par '/api' sont redirigées vers le back-end
    location /api {
        # 'back-end' correspond au nom du service défini dans docker-compose.yml
        proxy_pass http://back-end:5252;
    }
}
